_base_: base.yaml
images_path: /home/salmonuser/DigitalTwins/gluemap/Debug/SSSAligned02MiniHard/images/
write_path: results/scenes/SSSAligned02MiniHard/
rig_config_path: /home/salmonuser/DigitalTwins/gluemap/Debug/SSSAligned02MiniHard/schema.yaml
gt_intrinsics_path: null
